
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: bakehouseport
    port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: bakehouse
status:
  loadBalancer: {}
